# Created using wingetcreate 0.4.3.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.0.0.schema.json

PackageIdentifier: seac.cruscotto
PackageVersion: 1
PackageLocale: en-US
Publisher: Seac
PackageName: Cruscotto
License: MIT
ShortDescription: seac cruscotto
ManifestType: defaultLocale
ManifestVersion: 1.0.0
